### ISSUE TITLE
License

### ISSUE THREAD

**Issue by feamsr00** [jfsimon/scm#2]
Hi There,

What license is this under?

Thanks!

**Comment by jfsimon** [comment]
Hi @feamsr00 
I must admit I forgot this project exist ;-)
There is no license for now, MIT would be fine.
Are you interested by this repository?

**Comment by feamsr00** [comment]
Hi. I was curious in its functionality. I had been looking for a descent multipurpose VCS library. Alas, I have yet to find one. Thanks for your time!
